config/routes.rb
Rails.application.routes.draw do
  root 'gyms#index'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :relationships, only: [:create, :destroy]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    member do
      get :following, :followers
      get "quit"
      patch "withdraw"
    end
  end

  resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
  
  resources :contacts, only: [:new, :create]
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :gyms do
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resource :clips, only: [:create, :destroy]
    collection do
      get :search
      get :about
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gym
  has_many :comment_images, dependent: :destroy
  accepts_attachments_for :comment_images, attachment: :image

  
  NGWORD = %w(クソ野郎 糞野郎).freeze
  NGWORD_REGEX = %r{#{NGWORD.join('|')}}.freeze
  
  validates :comment_seq, uniqueness: { scope: [:user_id, :gym_id] }
  validates :comment, presence: true, length: { maximum: 500 }, format: { without: NGWORD_REGEX }

  attachment :comment_image
  #クラスメソッド　一つのジムに対して何個コメントしたかを取得
  # def users_comment_count
  #   user.comments.where(gym_id:self.gym_id).count
  # end

  def comment_seq_count
    comment_seq = Comment.where(gym_id: gym_id, user_id: user_id).maximum(:comment_seq)
    # 同Gym,Userにcomment_seqが存在すればcomment_seqの最大値に+1した値が次のコメントのcomment_seqとなる
    # 同Gym,Userにcomment_seqが存在しなければ次のコメントのcomment_seqは初期値の1となる
    if comment_seq
      comment_seq += 1
    else
      comment_seq = 1
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = Comment.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @comment = Comment.find(params[:id])
    @user = User.find(@comment.user_id)
    @gym = Gym.find(@comment.gym_id)
  end

  def edit
    @comment = Comment.find(params[:id])
    if @comment.user == current_user
      render 'edit'
    else
      redirect_to comment_path(@comment.id)
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_path(@comment.id),flash: {success: '編集に成功しました！'}
    else
      render 'edit'
    end
  end

  def create
    @gym = Gym.find(params[:gym_id])
    @comment = Comment.new(comment_params)
    @comment.gym_id = @gym.id
    @comment.user_id = current_user.id
    @comment.comment_seq = @comment.comment_seq_count
    @comments = @gym.comments.order(created_at: :desc).page(params[:page])
    if @comment.save
      render 'create'
    else
      render 'error'
    end
  end

  def destroy
    if params[:gym_id].present?
      @gym = Gym.find(params[:gym_id])
      comment = @gym.comments.find(params[:id])
      comment.destroy
      @comments = @gym.comments.order(created_at: :desc).page(params[:page])
    else
      @user = User.find(params[:user_id])
      comment = @user.comments.find(params[:id])
      comment.destroy
      @comments = @user.comments.order(created_at: :desc).page(params[:page])
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :comment_image)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<div>
  <% if comments.exists? %>
  <% comments.each do |comment| %>
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <%= link_to (comment.user) do %>
            <%= attachment_image_tag comment.user, :profile_image, size:'30x30', format: 'jpeg', class: "rounded-circle", fallback: "default_user.jpg" %>
            <%= comment.user.name %>
          <% end %>
          <a>投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %> <%= comment.comment_seq %>回目の訪問</a><!--コメントモデルでメソッドを定義-->
            <%= link_to (comment.gym) do %>
              <p class="comment_gym_name"><%= comment.gym.name %></p>
            <% end %>
        </div>
        <hr size="10">
        <div class="row">
          <div class="col-sm-3">
            <div class="card-text"><%= attachment_image_tag comment, :comment_image, :fill, 120, 120, format: 'jpeg' %></div>
          </div>
          <div class="col-sm-9">
            <div class="card-text"><%= comment.comment.truncate(50) %></div>
          </div>
        </div>
        <div class="row justify-content-center">
          <button type="button" class="btn btn-raised btn-primary" data-toggle="modal" data-target="#comment_modal<%= comment.id %>">全文を表示</button>
          <div class="modal fade" id="comment_modal<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="comment_modal<%= comment.id %>"><%= comment.user.name %>さんのコメント</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="comment-img"><%= attachment_image_tag comment, :comment_image, size: "400x400", format: 'jpeg' %></div>
                    </div>
                    <div class="col-sm-6">
                      <div class="text"><%= simple_format(comment.comment)%></div>
                    </div>
                  </div>
                  <div class="text-sm-center"><%= link_to "ノボログ詳細へ", comment_path(comment) %></div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% if user_signed_in? %>
        <div class="row justify-content-end">
          <% if comment.user == current_user || current_user.admin? %>
            <% if request.path.include?('gym') %>
                <div class="text"><%= link_to "削除", gym_comment_path(comment.gym,comment, page: params[:page]), class: "btn btn-danger btn-sm", data: {confirm: "Are you sure?"}, method: :delete, remote:true %></div>
            <% elsif request.path.include?('user') %>
                <div class="text"><%= link_to "削除", user_comment_path(comment.user,comment, page: params[:page]), class: "btn btn-danger btn-sm", data: {confirm: "Are you sure?"}, method: :delete, remote:true %></div>
            <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% else %>
    <div class="row justify-content-center">まだノボログがありません</div>
  <% end %>
</div>

app/views/comments/create.js.erb
$("#comments_count").html("<%= @comments.count %>件のノボログ");　
$("#gym_comments").html("<%= j(render partial: 'comments/index', locals: {comments: @comments, gym: @gym, user: @user}) %>");
$("#comment_comment").val("");

app/views/comments/destroy.js.erb
$("#comments_count").html("<%= @comments.count %>件のノボログ");　
$("#gym_comments").html("<%= j(render partial: 'comments/index', locals: {comments: @comments, gym: @gym, user: @user}) %>");
$("#comment_comment").val("");

app/views/comments/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
      <h1 class="display-4">ノボログ編集</h1>
      <hr class="my-4"><h1><%= @comment.gym.name %></h1>
      <a><%= @comment.comment_seq %>回目の訪問</a><!--コメントモデルでメソッドを定義-->
      <a><%= @comment.created_at.strftime('%Y/%m/%d') %></a>
      <div class="row justify-content-center">
       <div><%= form_with model:@comment, local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div><%= f.label :image, "投稿画像" %></div>
          <div><%= attachment_image_tag @comment, :comment_image, size:"400x400", format: 'jpeg', class: "rounded", fallback: "gym_default.jpg" %>
          </div>
          <div>新しい画像</div>
          <div><img id="preview" style="width:40%;"></div>
          <div><%= f.attachment_field :comment_image %></div>
          <div><%= f.label :comment, "ノボログ内容" %></div>
          <div><%= f.text_area :comment, autofocus: true, autocomplete: 'ノボログ', class: "form-control" %></div>
          <div class="row justify-content-center">
              <%= f.submit "編集を完了する", class:"btn btn-raised btn-info" %>
              <% end %>
          </div>
          <div class="row justify-content-center">
            <%= link_to "戻る", comment_path(@comment), class:"btn btn-primary"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/error.js.erb
$('#comments_error').html("<%= j(render 'layouts/error_messages', model: @comment) %>");

app/views/comments/index.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
            <h4>新着ノボログ</h4>
            <div id="gym_comments">
              <%= render 'comments/index', comments: @comments, gym: @gym, user: @user %>
            </div>
            <div class="row justify-content-center">
                <%= paginate @comments %>
            </div>
        </div>
    </div>
</div>

app/views/comments/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
      <% if @user.id == current_user.id %>
      <div class="row justify-content-end">
          <%= link_to edit_comment_path(@comment), class: 'btn btn-raised btn-dark' do %>
            <i class="fa fa-tools fa-sm"></i>
            <span>ノボログ編集</span>
          <% end %>
      </div>
      <% end %>
      <div class="row">
        <%= link_to (@comment.gym) do %>
          <h2><%= @comment.gym.name %></h2>
        <% end %>
      </div>
      <div class="row"><p><%= @comment.gym.address.truncate(20) %></p></div>
      <div class="row">
        <%= link_to "施設情報", gym_path(@gym), class:"btn btn-raised btn-primary" %>
      </div>
      <hr size="10">
      <div class="row">
        <div class="user-info">
          <%= link_to (@comment.user) do %>
            <%= attachment_image_tag @comment.user, :profile_image, size:'50x50', format: 'jpeg', class: "rounded-circle", fallback: "default_user.jpg" %>
            <%= @comment.user.name %>
          <% end %>
          <a class="comment-info">投稿日：<%= @comment.created_at.strftime('%Y/%m/%d') %></a>
          <a class="comment-info"><%= @comment.comment_seq %>回目の訪問</a><!--コメントモデルでメソッドを定義-->
        </div>
      </div>
      <div class="row">
          <div class="col-sm-3">
            <div class="comment-img"><%= attachment_image_tag @comment, :comment_image, size: "400x400", format: 'jpeg' %></div>
          </div>
          <div class="col-sm-7">
            <div class="text"><%= simple_format(@comment.comment)%></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>