config/routes.rb
Rails.application.routes.draw do
  root 'gyms#index'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :relationships, only: [:create, :destroy]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    member do
      get :following, :followers
      get "quit"
      patch "withdraw"
    end
  end

  resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
  
  resources :contacts, only: [:new, :create]
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :gyms do
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resource :clips, only: [:create, :destroy]
    collection do
      get :search
      get :about
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
      
  def create
    @user = User.find(params[:id])
    current_user.follow(params[:id])
    render 'create'
  end
  
  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(params[:id])
    render 'destroy'
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if current_user.following?(user) %>
    <%= link_to unfollow_path(user.id), method: :POST, remote: true, class: "btn btn-raised btn-danger btn-sm" do %>
        <i class="fa fa-user-circle"></i>
        <span>フォロー解除</span>
    <% end %>
<% else %>
    <%= link_to follow_path(user.id), method: :POST, remote: true, class: "btn btn-raised btn-info btn-sm" do %>
        <i class="fa fa-user-circle"></i>
        <span>フォローする</span>
    <% end %>
<% end %>

app/views/relationships/_follow_stats.html.erb
  <div class="col-sm-3">
    <%= link_to user_path(user) do %>
      <i class="btn btn-raised btn-secondary far fa-clipboard" aria-hidden="true">　<%= user.name %>さんのノボログ <%= user.comments.count %></i>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= link_to following_user_path(user) do %>
      <i class="btn btn-raised btn-secondary fa fa-user-circle" aria-hidden="true">
        <span id="follower_count_<%= user.id %>"><%= user.name %>さんのフォロー</span></i>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= link_to followers_user_path(user) do %>
      <i class="btn btn-raised btn-secondary fa fa-user-circle" aria-hidden="true">
        <span id="followed_count_<%= user.id %>"><%= user.name %>さんのフォロワー</span></i>
    <% end %>
  </div>
  <div class="col-sm-3">
    <% if user.id == current_user.id %>
      <%= link_to edit_user_path(user), data: {"turbolinks" => false}, class: 'btn btn-raised btn-dark btn-sm' do %>
        <i class="fa fa-tools fa-sm"></i>
        <span>登録情報編集</span>
      <% end %>
    <% else user.id != current_user.id %>
      <div id="follow_btn">
        <%= render 'relationships/follow', user: user %>
      </div>
    <% end %>
  </div>

app/views/relationships/create.js.erb
$('#follow_btn').html("<%= j(render 'relationships/follow',{ user: @user }) %>");

app/views/relationships/destroy.js.erb
$('#follow_btn').html("<%= j(render 'relationships/follow',{ user: @user }) %>");