config/routes.rb
Rails.application.routes.draw do
  root 'gyms#index'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :relationships, only: [:create, :destroy]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    member do
      get :following, :followers
      get "quit"
      patch "withdraw"
    end
  end

  resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
  
  resources :contacts, only: [:new, :create]
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :gyms do
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resource :clips, only: [:create, :destroy]
    collection do
      get :search
      get :about
    end
  end
end

app/models/gym.rb
class Gym < ApplicationRecord
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/.freeze
  NGWORD = %w(クソ野郎 糞野郎).freeze
  NGWORD_REGEX = %r{#{NGWORD.join('|')}}.freeze

  has_many :comments, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_many :clip_gyms, through: :clips, source: :gym # ユーザーがブックマークしたジムを定義
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  attachment :gym_image

  validates :name, presence: true, length: { in: 2..50 }, uniqueness: true, format: { without: NGWORD_REGEX }
  validates :introduction, length: { in: 0..500 }, format: { without: NGWORD_REGEX }, allow_blank: true
  validates :tel, format: { with: VALID_PHONE_NUMBER_REGEX }, uniqueness: true, allow_blank: true
  validates :address, uniqueness: true, format: { without: NGWORD_REGEX }, allow_blank: true
  validates :url, uniqueness: true, format: { without: NGWORD_REGEX }, allow_blank: true
  validates :open_time, length: { maximum: 150 }, format: { without: NGWORD_REGEX }
  validates :price, length: { maximum: 200 }, format: { without: NGWORD_REGEX }
  validates :holiday, length: { maximum: 200 }, format: { without: NGWORD_REGEX }
  validates :access, length: { maximum: 500 }, format: { without: NGWORD_REGEX }

  def cliped_by?(user) # ジムをブックマークしてあるかどうか
    clips.where(user_id: user.id).exists?
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show,:about,:search]
  before_action :admin_user, only: :destroy

  def index
    # @random = Gym.order("RAND()").limit(5)
    @gyms = Gym.page(params[:page]).per(21).reverse_order
    # 20件表示
  end
  
  def about
  end
  
  def new
    @gym = Gym.new
  end

  def create
    @gym = Gym.new(gym_params)
    @gym.user_id = current_user.id
    if @gym.save
      redirect_to gym_path(@gym.id),flash: {success: 'ジムの登録ありがとうございます!'}
    else
      render 'new'
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])
    @gym.user_id = current_user.id #更新したユーザーの名前を保存する
    if @gym.update(gym_params)
      redirect_to gym_path(@gym.id), flash: {success:  '編集に成功しました'}
    else
      render 'edit'
    end
  end

  def show
    @gym = Gym.find(params[:id])
    @comment = Comment.new
    @comments = @gym.comments.order(created_at: :desc).page(params[:page])
  end

  def destroy
    @gym = Gym.find(params[:id])
    @gym.destroy
    redirect_to gyms_path, flash: {success:  'ジム情報を削除しました'}
  end

  private

  def gym_params
    params.require(:gym).permit(:name, :introduction, :tel, :gym_image,
                                :address, :postcode, :url, :open_time, :price, :holiday,
                                :access, :latitude, :longitude)
  end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card" style="background: rgba(255,255,255,0.9)">
      <div class="card-body">
        <div class="card-title">ジム情報登録</div>
        <div class="card-text-center">
         <div class="form-group">
            <%= form_with model:gym, local:true do |f| %>
              <%= render 'layouts/error_messages', model: f.object %>
              <div><%= f.label :image, "ジム画像" %></div>
              <div class="row justify-content-center"><img id="preview" style="width:40%;"></div>
              <div class="row justify-content-center"><%= f.attachment_field :gym_image %></div>
              <div><%= f.label :name %></div>
              <div><%= f.text_field :name, class: "form-control", placeholder:"例：B-PUMP TOKYO" %></div>
              <div><%= f.label :address %></div>
              <div><%= f.text_area :address,  class: "form-control", placeholder:"例：東京都文京区湯島１丁目１−８"  %></div>
              <div><%= f.label :tel %></div>
              <div><%= f.text_field :tel,  class: "form-control", placeholder:"例：03-6206-9189" %></div>
              <div><%= f.label :open_time %></div>
              <div><%= f.text_area :open_time,  class: "form-control", placeholder:"例：平日	12:00～23:00"  %></div>
              <div><%= f.label :price %></div>
              <div><%= f.text_area :price,  class: "form-control", placeholder:"例：平日・通日	2,000円(税抜)"  %></div>
              <div><%= f.label :holiday %></div>
              <div><%= f.text_area :holiday,  class: "form-control", placeholder:"例：年中無休"  %></div>
              <div><%= f.label :access %></div>
              <div><%= f.text_area :access,  class: "form-control", placeholder:"例：JR「秋葉原駅」徒歩5分"  %></div>
              <div><%= f.label :url %></div>
              <div><%= f.text_field :url,  class: "form-control", placeholder:"URL"  %></div>
              <div><%= f.label :introduction %></div>
              <div><%= f.text_area :introduction,  class: "form-control", placeholder:"課題の傾向や特徴、紹介したいこと" %></div>
              <div class="row justify-content-center">
              <%= f.submit "登録を完了する", class:"btn btn-raised btn-success" %>
            <% end %>
              <% if current_user.admin? %>
                <%= link_to "ジム情報を削除", @gym, class: "btn btn-raised btn-danger", data: {confirm: "本当に削除してよろしいですか?"}, method: :delete %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gyms/_index.html.erb
<% gyms.each do |gym| %>
    <div class="card card-image">
        <div class="embed-responsive">
            <%= link_to gym_path(gym.id) do %>
                <%= attachment_image_tag gym, :gym_image, size:"400x300", fallback: "gym_default.jpg" %>
            <% end %>
        </div>
      <div class="card-body text-center text-white pb-0" style="background-color:#353132">
        <div class="card-title"><%= gym.name %></div>
        <div class="card-text text-left">
            <p>住所：<%= gym.address %></p>
            <p>定休日：<%= gym.holiday %></p>
            <p>営業時間：<%= gym.open_time %></p>
            <p class="text-right"><%= link_to "READ MORE>>", gym_path(gym.id) %></p>
        </div>
        <div class="card-footer mt-4" style="background-color:#353132">
            <i class="far fa-comments px-2" ><%= gym.comments.count %></i>
            <span class="px-2" id="clips_btns_<%= gym.id %>"> 
                <%= render partial: 'clips/clip', locals: {gym: gym} %>
            </span>
        </div>
      </div>
    </div>
<% end %>

app/views/gyms/about.html.erb
<div class="about">
    <div class="col-sm-12">
        <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
            <div class="text-center">
                <%= image_tag 'logo.png' %>
            </div>
            <div class="row justify-content-center">
                <div class=" title text-center">
                <p>初めていくジムがどんな雰囲気なのかわからず、気後れしてしまうことありませんか？</p>
                <p>ジムに行く前にKABESHIRUで検索すれば先輩クライマーのジムレビューが確認できます！</p>
                <p>また、今日はどのジムでどれだけ登ったか、今日完登できなかった課題はどれか・・・</p>
                <p>など、自分のトレーニング記録（ノボログ）もつけられます。</p>
                <p>KABESHIRUはクライマーライフをちょっぴり豊かにするサイトです。</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/gyms/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
      <h1 class="display-4"><%= @gym.name %>の情報登録</h1>
      <hr class="my-4">
      <p>ボルダリングジム登録の協力をお願いします。</p>
      <p>入力項目が多数あるので、不明な箇所は未入力のままでも登録できます。</p>
      <p>一度ジムを登録した後は壁シルのユーザーなら誰でも情報を編集することができます。</p>
      <p>既に同じジムが登録されている場合は後から登録したページは削除されますのでご注意ください。</p>
    </div>
  </div>
</div>
<%= render "form", gym: @gym %>

app/views/gyms/index.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
            <div class="row justify-content-center">
                <%= image_tag 'logo.png' %>
            </div>
            <div class="row justify-content-center">
                <p class="title">今日登りたい課題が見つかるボルダリングジム検索サイト</p>
            </div>
            <div class="row justify-content-center">
                <%= search_form_for @search, class:"form-group label-floating",url: search_gyms_path do |f| %>
                <%= f.text_field :name_or_address_or_introduction_cont, placeholder: "施設名、エリア、登ってみたい壁を入力してください...", size: "100x10", class: 'input form-control' %>
                <button class="btn btn-raised btn-info btn-lg btn-block" type="submit">検索</button>
                <% end %>
            </div>
            <div class="row justify-content-center">
                <p class="title">あなたのお気に入りのジムがない時は今すぐ登録しましょう！</p>
            </div>
            <div class="text-center">
                <%= link_to 'ジム登録', new_gym_path, class: "btn btn-raised btn-primary btn-lg" %>
            </div>
            <% unless user_signed_in? %> 
            <div class="row justify-content-center">
                <div class="info-btn">
                    <%= link_to '新規登録', new_user_registration_path, class: "btn btn-info btn-lg" %>
                </div>
                <div class="info-btn">
                    <%= link_to 'ログイン', new_user_session_path, class: "btn btn-success btn-lg" %>
                </div>
            </div>
            <div class="row justify-content-center">
                <%= link_to 'ゲストログイン（ポートフォリオ閲覧の方はこちら）', users_guest_sign_in_path, method: :post %>
            </div>
            <% end %>
        </div>
    </div>
</div>
<!--余裕があればランダムで表示-->
<div class="card-columns">
    <%= render 'gyms/index', gyms: @gyms, gym: @gym %>
</div>
<div class="row justify-content-center">
    <%= paginate @gyms %>
</div>

app/views/gyms/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
      <h1 class="display-4">ジム情報登録</h1>
      <hr class="my-4">
      <p>ボルダリングジム登録の協力をお願いします。</p>
      <p>入力項目が多数あるので、不明な箇所は未入力のままでも登録できます。</p>
      <p>一度ジムを登録した後は壁シルのユーザーなら誰でも情報を編集することができます。</p>
      <p>既に同じジムが登録されている場合は後から登録したページは削除されますのでご注意ください。</p>
    </div>
  </div>
</div>
<%= render "form", gym: @gym %>

app/views/gyms/search.html.erb
<div class="row">
    <div class="col-12">
        <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
            <div class="row justify-content-center">
                <%= search_form_for @search, url: search_gyms_path do |f| %>
                <%= f.text_field :name_or_address_or_introduction_cont, placeholder: "施設名、エリア、登ってみたい壁を入力してください...", size: "100x10", class: 'form-control' %>
                <button class="btn btn-raised btn-info btn-lg btn-block" type="submit">検索</button>
                <% end %>
            </div>
        <% if params[:q]['name_or_address_or_introduction_cont'] == "" %>
            <div class="row justify-content-center"><p>検索キーワードがありません</p></div>
        <% elsif @search_gyms.present? %>
            <div class="row justify-content-center"><%= "「#{params[:q]['name_or_address_or_introduction_cont']}」の検索結果: #{@search_gyms.count}件" %></div>
        </div>
    </div>
</div>
<div class="col-12">
    <div class="card-columns">
        <%= render 'gyms/index', gyms: @search_gyms, gym: @gym %>
    </div>
</div>
<%= paginate @search_gyms %>
<% else %>
<div class="row justify-content-center">
    <p>検索に一致するジムはありませんでした。</p>
    <p>キーワードを変えて検索してみてください</p>
</div>
<div class="row justify-content-center">
    <a>登ったジムの情報がなければ是非登録をお願いします</a>
</div>    
<div class="row justify-content-center">
    <%= link_to 'ジム登録', new_gym_path, class: "btn btn-primary btn-lg" %>
</div>
<% end %>

app/views/gyms/show.html.erb
<div class="row">    
  <div class="col-sm-12">
    <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
      <div class="row justify-content-end">
        <div class="user_name">
          最新更新ユーザー：<%= link_to @gym.user.name, @gym.user %></br>
          最新更新日：<%= @gym.updated_at.strftime('%Y/%m/%d') %></br>
        </div>
      </div>
      <div class="row justify-content-center">
        <h1><%= @gym.name %></h1>
      </div>
      <div class="row">
        <div class="col-sm-12 text-right">
          <a id="comments_count"><%= @gym.comments.count %>件のノボログ</a>
          <span class="px-2" id="clips_btns_<%= @gym.id %>"> 
          <%= render partial: 'clips/clip', locals: {gym: @gym} %>
          </span>
        </div>
      </div>
      <hr size="10">
      <div class="row">
        <div class="col-sm-12 text-left">
          <span id="go_comment">
            <a href="#nobolog"><i class="btn btn-raised btn-secondary far fa-edit"> 投稿する</i></a>
          </span>
          <span id="go_info">
            <a href="#gym_info"><i class="btn btn-raised btn-secondary far fa-arrow-alt-circle-down"> ジム詳細</i></a>
          </span>
          <span id="go_index">
            <a href="#gym_index"><i class="btn btn-raised btn-secondary far fa-comments"> ノボログ一覧</i></a>
          </span>
        </div>
      </div>
      <span id="gym_info"></span>
    </div>
  </div>
</div>
<div class="row"> 
  <div class="col-sm-6">
    <div class="card" style="background: rgba(255,255,255,0.9)">
      <div class="card-body">
        <div class="card-text text-center">
          <div class="embed-responsive"><%= attachment_image_tag @gym, :gym_image, size:"400x400", format: 'jpeg', class: "rounded", fallback: "gym_default.jpg" %></div>
          <div class="row"> 
            <div id="map"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card" style="background: rgba(255,255,255,0.9)">
      <div class="card-body">
        <div class="card-title">Gym info</div>
          <div class="text-sm-right">
            <%= link_to edit_gym_path, class: 'btn btn-raised btn-dark' do %>
            <i class="fa fa-tools"></i>
            <span>情報修正</span>
            <% end %>
          </div>
        	<hr size="10">
        <div class="card-text">
          <div class="table table-responsive ">
            <table class="text-nowrap">
              <tr>
                <th>住所</th>
                <td><%= @gym.address %></td>
              </tr>
              <tr>
                <th>電話番号</th>
                <td><%= @gym.tel %></td>
              </tr>
              <tr>
                <th>営業時間</th>
                <td><%= simple_format(@gym.open_time) %></td>
              </tr>
              <tr>
                <th>利用料金</th>
                <td><%= simple_format(@gym.price) %></td>
              </tr>
              <tr>
                <th>定休日</th>
                <td><%= simple_format(@gym.holiday) %></td>
              </tr>
              <tr>
                <th>公式HP</th>
                <td><%= @gym.url %></td>
              </tr>
              <tr>
                <th>アクセス</th>
                <td><%= simple_format(@gym.access) %></td>
              </tr>
              <tr>
                <th>ジム紹介</th>
                <td><%= simple_format(@gym.introduction) %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section id="nobolog">
<div class="row">
  <div class="col-sm-12">
    <div class="jumbotron" style="background: rgba(255,255,255,0.9)">
      <div class="card-title">Photo</div>
      <hr class="my-4">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <% @gym.comments.first(1).each do |comment| %>
              <%= attachment_image_tag comment, :comment_image, :fill, 100, 100, format: 'jpeg' %>
            <% end %>
          </div> 
          <div class="carousel-item">
            <% @gym.comments.drop(1).each do |comment| %>
              <%= attachment_image_tag comment, :comment_image, :fill, 100, 100, format: 'jpeg' %>
            <% end %>
          </div> 
        </div>
        <div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="card" style="background: rgba(255,255,255,0.9)">
      <div class="card-body">
        <div class="card-title"><%= @gym.name %>のノボログ一覧</div>
        <hr size="10">
        <div class="card-text">
          <div id="comments_error">
            <%= render 'layouts/error_messages', model: @comment %>
          </div>
          <div class="form_group">
            <%= form_with model:[@gym,@comment], url: gym_comments_path(gym_id: @gym.id, page: params[:page]) do |f| %>
            <%= f.label :image, "登った課題の写真も投稿できます" %>
            <div class="row justify-content-center">
              <img id="preview" style="width:40%;">
            </div>
            <div class="row justify-content-center">
              <%= f.attachment_field :comment_image %>
            </div>
            
            <div class="form-group">
            <label>登った本数、課題について、書き込んでみましょう</label>
              <%= f.text_area :comment, size:"100x7", class: "form-control", placeholder: "例：今日は3級課題を5本登れたよ！" %>
              <%= f.submit "ノボッタ！", class: "btn btn-raised btn-warning btn-lg btn-block" %>
              <% end %>
            </div>
          </div>
        </div>
        <section id="gym_index">
        <div class="row">
          <div class="col-sm-12">
            <div id="gym_comments">
              <%= render 'comments/index', comments: @comments, gym: @gym, user: @user %>
            </div>
            <%= paginate @comments %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
<style type="text/css">
  #map { height: 400px;
    width: 100%;}

</style>

<script type="text/javascript">
    function initMap() {

        

        var test ={lat: <%= @gym.latitude %>, lng: <%= @gym.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @gym.address %>';

        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>