config/routes.rb
Rails.application.routes.draw do
  root 'gyms#index'
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :relationships, only: [:create, :destroy]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    member do
      get :following, :followers
      get "quit"
      patch "withdraw"
    end
  end

  resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
  
  resources :contacts, only: [:new, :create]
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :gyms do
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resource :clips, only: [:create, :destroy]
    collection do
      get :search
      get :about
    end
  end
end

app/views/layouts/_error_messages.html.erb
<div>
    <% if model.errors.any? %> 
        <div class = "alert alert-warning">
            <ul>
                <% model.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
<div class="col-sm-12">
    <div class="alert alert-<%= message_type %>">
        <%= message %>
    </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= link_to root_path, class: "nav-link" do %><span class="logo">KABESHIRU</span><% end %>
      <ul class="menu">
        <li class="name">© tota 2021</li>
      </ul>
      </div>
      <div class="col-md-4">
        <ul class="menu">
          <span>ジムを探す</span>   
          <li class="nav-item">
            <%= link_to "/", class: "nav-link" do %><i class="fas fa-search">ジムを探す</i><% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_gym_path, class: "nav-link" do %><i class="fas fa-edit">施設登録</i><% end %>
          </li>
          <li class="nav-item">
              <%= link_to comments_path, class: "nav-link" do %><i class="fas fa-comments">ノボログ一覧</i><% end %> 
            </li>
         </ul>
      </div>
      <div class="col-md-4">
        <ul class="menu">
          <span>KABESHIRUとは</span>   
          <li class="nav-item">
            <%= link_to about_gyms_path, class: "nav-link" do %><i class="fas fa-question-circle">About</i><% end %> 
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar fixed-top navbar-light navbar-expand-lg" style="background: rgba(230,231,232)">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><%= image_tag 'logo.png' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#responsiveMenu" aria-controls="responsiveMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="responsiveMenu">
        <ul class="navbar-nav ml-left">
          <li class="nav-item">
            <%= link_to gyms_path, class: "nav-link" do %><i class="fas fa-warehouse">Gyms</i><% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_gyms_path, class: "nav-link" do %><i class="fas fa-question-circle">About</i><% end %>
          </li>
          <li class="nav-item">
            <%= link_to comments_path, class: "nav-link" do %><i class="fas fa-comments">Nobolog</i><% end %> 
          </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to '全ユーザー一覧', users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ジム登録', new_gym_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <%= link_to "管理者権限", user_path(current_user), class: "nav-link"%>
              </li>
              <li class="form-inline">
                <%= render "layouts/search_form", search:@search %>
              </li>
            </ul>
          <% else %>  
          <li class="nav-item">
            <%= link_to new_gym_path, class: "nav-link" do %><i class="fas fa-edit">ジム登録</i><% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %><i class="fas fa-sign-out-alt">Logout</i><% end %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link" do %>
                ようこそ<%= attachment_image_tag current_user, :profile_image, size:'40x40', format: 'jpeg', class: "rounded-circle", fallback: "default_user.jpg" %>
                <%= (current_user.name) %>さん
              <% end %>
          </li>
          <li class="form-inline">
            <%= render "layouts/search_form", search:@search %>
          </li>
        </ul>
          <% end %>
        <% else %>
            <li class="nav-item">
                <%= link_to new_user_registration_path, class: "nav-link" do %><i class="fas fa-user-plus">SignUP</i><% end %>
            </li>
            <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link" do %><i class="fas fa-sign-in-alt">LogIn</i><% end %>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="form-inline">
                <%= render "layouts/search_form", search:@search %>
            </li>
        <% end %>
          </ul>
      </div>
    </div>  
  </nav>
</header>

app/views/layouts/_search_form.html.erb
<%= search_form_for search, url: search_gyms_path do |f| %>
  <%= f.text_field :name_or_address_or_introduction_cont, placeholder: "検索ワードをどうぞ...", class: 'input form-control' %>
  <button class="btn btn-raised btn-info" type="submit"><i class="fas fa-search"></i></button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <%= csrf_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <!-- Material Design for Bootstrap fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link href="https://fonts.googleapis.com/css2?family=Karantina&family=Kosugi&family=Noto+Sans+JP:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <!-- Material Design for Bootstrap CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

    <title>壁シル</title>
  </head>
  <body>
    <div class="bg">
      <%= render 'layouts/header' %>
      <main class="container">
      <%= render 'layouts/flash_message' %>
      <%= yield %>
      </main>
      <%= render 'layouts/footer' %>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
    <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>    </div>
  </body>
</html>